/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/app-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minimum supported native app build, for the client's force-update check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppVersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment owned by the caller (404, never 403, if not owned/found) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description comment id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/djs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a DJ (or return the existing one, deduped by spotifyId then slug) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description DJ to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["createDjRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dj"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/djs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search DJs by name, most-reviewed first */
        get: {
            parameters: {
                query?: {
                    /** @description name search; omit for the most-reviewed DJs */
                    q?: string;
                    /** @description max results, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dj"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/djs/spotify-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Spotify for artists (fails open to [] on Spotify errors) */
        get: {
            parameters: {
                query: {
                    /** @description search query */
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpotifyArtist"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/djs/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews for a DJ, cursor-paginated by seenAt desc */
        get: {
            parameters: {
                query?: {
                    /** @description pagination cursor (RFC3339 seenAt of the last item) */
                    cursor?: string;
                    /** @description page size, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description DJ id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedReviews"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/djs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a DJ by slug, with rating aggregate and recent reviews */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description DJ slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DjDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or search events (named parties like "Innervisions NY"), most-reviewed first */
        get: {
            parameters: {
                query?: {
                    /** @description name search; omit to list all */
                    q?: string;
                    /** @description max results, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event with its totals, the DJs and venues it's been logged with, and recent reviews */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description event slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity feed: followed users' reviews interleaved with popular ones every 4th item */
        get: {
            parameters: {
                query?: {
                    /** @description pagination cursor (opaque, encodes createdAt + popular-pool offset) */
                    cursor?: string;
                    /** @description page size, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most-liked-and-commented reviews, ranked */
        get: {
            parameters: {
                query?: {
                    /** @description page size, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PopularResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/is-following/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the caller follows the given user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description user id */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FollowingStatusResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description user id to follow */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        /** Unfollow a user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description user id to unfollow */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard scoped to the caller and everyone they follow */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardEntry"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a night out: the event (picked, or found or created by name), venue, day, lineup, and the night and DJ reviews, in one go */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description the night to log */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["createNightLogRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NightLogResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a review with its relations, engagement, and tagged users */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a review owned by the caller (404, never 403, if not owned/found) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a review owned by the caller (404, never 403, if not owned/found) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            /** @description fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["updateReviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/reviews/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a review's comments, oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewComment"][];
                    };
                };
            };
        };
        put?: never;
        /** Add a comment to a review */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            /** @description comment body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["addCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewComment"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Like a review */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        /** Unlike a review */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description review id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the tag library (defaults plus every tag users have added), most used first */
        get: {
            parameters: {
                query?: {
                    /** @description filter to tags containing this text */
                    q?: string;
                    /** @description max results, 1-50, default 30 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the caller's own user row */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the caller's own profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["updateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace the caller's showcased favorite reviews (0-3, ordered, #1 first) - reviews must be the caller's own */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ordered review ids, at most 3, no duplicates */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["setFavoritesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FavoriteReviewsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/me/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register this device's Expo push token for the caller (moves it from any other account) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["pushTokenRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        /** Stop sending the caller's notifications to this device (on sign-out) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["pushTokenRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search users by username or display name, most-followed first */
        get: {
            parameters: {
                query?: {
                    /** @description name search; omit for the most-followed users */
                    q?: string;
                    /** @description max results, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the users who follow the given user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description user id */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the users the given user follows */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description user id */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's profile by username, with follow/review counts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description username */
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's showcased favorite reviews (top 3, ordered, #1 first) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description username */
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FavoriteReviewsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's reviews, cursor-paginated by seenAt desc */
        get: {
            parameters: {
                query?: {
                    /** @description pagination cursor (RFC3339 seenAt of the last item) */
                    cursor?: string;
                    /** @description page size, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description username */
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedReviews"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's review stats: totals, top DJs, top venues */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description username */
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStatsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/places-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Google Places for venues not yet saved
         * @description Pass the same client-generated sessionToken on every keystroke of one search and on the POST /api/logs that saves the picked place, so Google bills them as one session.
         */
        get: {
            parameters: {
                query: {
                    /** @description search query */
                    q: string;
                    /** @description Places autocomplete session token */
                    sessionToken?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaceSuggestion"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search saved venues by name, busiest first */
        get: {
            parameters: {
                query?: {
                    /** @description name search; omit for the busiest venues */
                    q?: string;
                    /** @description max results, 1-50, default 20 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VenueSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a venue by id, with the events logged there and recent reviews */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description venue id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VenueDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppVersionResponse: {
            iosUpdateUrl: string;
            minIosBuild: number;
        };
        Dj: {
            bio: string;
            createdAt: string;
            createdByUserId: string;
            genres: string[];
            id: string;
            imageUrl: string;
            name: string;
            slug: string;
            spotifyId: string;
            updatedAt: string;
        };
        DjDetailResponse: {
            avgRating: number;
            dj: components["schemas"]["Dj"];
            /**
             * @description RatingCounts is how many reviews gave each star rating: index 0 is
             *     1 star, index 4 is 5 stars.
             */
            ratingCounts: number[];
            recentReviews: components["schemas"]["ReviewDTO"][];
            reviewCount: number;
        };
        Event: {
            createdAt: string;
            createdByUserId: string;
            id: string;
            name: string;
            slug: string;
        };
        EventDetailResponse: {
            djs: components["schemas"]["EventDj"][];
            event: components["schemas"]["EventSummary"];
            recentReviews: components["schemas"]["ReviewDTO"][];
            venues: components["schemas"]["EventVenue"][];
        };
        EventDj: {
            dj: components["schemas"]["Dj"];
            logCount: number;
        };
        EventSummary: {
            avgRating: number;
            createdAt: string;
            createdByUserId: string;
            id: string;
            logCount: number;
            name: string;
            reviewCount: number;
            slug: string;
        };
        EventVenue: {
            city: string;
            id: string;
            logCount: number;
            name: string;
        };
        FavoriteReviewsResponse: {
            items: components["schemas"]["ReviewDTO"][];
        };
        FeedResponse: {
            followingCount: number;
            items: components["schemas"]["ReviewDTO"][];
            nextCursor: string;
        };
        FollowingStatusResponse: {
            following: boolean;
        };
        LeaderboardEntry: {
            reviewCount: number;
            user: components["schemas"]["User"];
        };
        Log: {
            city: string;
            createdAt: string;
            /** @description EventID is nil for a night with no event name (just a venue). */
            eventId: string;
            id: string;
            /**
             * @description IsDay and IsNight say when this person went; both is day into night.
             *     At least one is set.
             */
            isDay: boolean;
            isNight: boolean;
            seenAt: string;
            userId: string;
            /**
             * @description Venue is the venue's display name, denormalized alongside VenueID.
             *     Both are nil only on logs migrated from reviews that had no night.
             */
            venue: string;
            venueId: string;
        };
        LogDTO: {
            city: string;
            createdAt: string;
            event: components["schemas"]["Event"];
            /** @description EventID is nil for a night with no event name (just a venue). */
            eventId: string;
            id: string;
            /**
             * @description IsDay and IsNight say when this person went; both is day into night.
             *     At least one is set.
             */
            isDay: boolean;
            isNight: boolean;
            lineup: components["schemas"]["Dj"][];
            seenAt: string;
            userId: string;
            /**
             * @description Venue is the venue's display name, denormalized alongside VenueID.
             *     Both are nil only on logs migrated from reviews that had no night.
             */
            venue: string;
            venueId: string;
        };
        NightLogResponse: {
            /** @description Event is nil for a night with no event name. */
            event: components["schemas"]["Event"];
            log: components["schemas"]["Log"];
            reviews: components["schemas"]["Review"][];
        };
        PaginatedReviews: {
            items: components["schemas"]["ReviewDTO"][];
            nextCursor: string;
        };
        PlaceSuggestion: {
            name: string;
            placeId: string;
            /**
             * @description SecondaryText is the rest of the place's description, usually its
             *     street address and city.
             */
            secondaryText: string;
        };
        PopularResponse: {
            items: components["schemas"]["ReviewDTO"][];
        };
        Review: {
            createdAt: string;
            /** @description DjID is nil for a review of the night as a whole. */
            djId: string;
            id: string;
            logId: string;
            rating: number;
            reviewText: string;
            /** @description SeenAt mirrors the log's, kept here for ordering and pagination. */
            seenAt: string;
            updatedAt: string;
            userId: string;
        };
        ReviewComment: {
            body: string;
            createdAt: string;
            id: string;
            reviewId: string;
            user?: components["schemas"]["User"];
            userId: string;
        };
        ReviewDTO: {
            commentCount?: number;
            createdAt: string;
            dj?: components["schemas"]["Dj"];
            /** @description DjID is nil for a review of the night as a whole. */
            djId: string;
            id: string;
            isLikedByMe?: boolean;
            isPopular?: boolean;
            likeCount?: number;
            /**
             * @description Log is the night out this review is part of: event, venue, date,
             *     day/night and lineup.
             */
            log?: components["schemas"]["LogDTO"];
            logId: string;
            rating: number;
            reviewText: string;
            /** @description SeenAt mirrors the log's, kept here for ordering and pagination. */
            seenAt: string;
            taggedUsers: components["schemas"]["User"][];
            tags: string[];
            updatedAt: string;
            user?: components["schemas"]["User"];
            userId: string;
        };
        SpotifyArtist: {
            genres: string[];
            imageUrl: string;
            name: string;
            spotifyId: string;
        };
        SuccessResponse: {
            success: boolean;
        };
        TagSummary: {
            id: string;
            isDefault: boolean;
            name: string;
            useCount: number;
        };
        TopDj: {
            dj: components["schemas"]["Dj"];
            reviewCount: number;
        };
        TopVenue: {
            reviewCount: number;
            venue: string;
        };
        User: {
            avatarUrl: string;
            bio: string;
            createdAt: string;
            displayName: string;
            id: string;
            updatedAt: string;
            username: string;
        };
        UserProfileResponse: {
            followerCount: number;
            followingCount: number;
            reviewCount: number;
            user: components["schemas"]["User"];
        };
        UserStatsResponse: {
            topDjs: components["schemas"]["TopDj"][];
            topVenues: components["schemas"]["TopVenue"][];
            totalReviews: number;
            uniqueDjs: number;
        };
        VenueDetailResponse: {
            events: components["schemas"]["VenueEvent"][];
            recentReviews: components["schemas"]["ReviewDTO"][];
            venue: components["schemas"]["VenueSummary"];
        };
        VenueEvent: {
            event: components["schemas"]["Event"];
            logCount: number;
        };
        VenueSummary: {
            address: string;
            city: string;
            googlePlaceId: string;
            id: string;
            /** @description LogCount is how many nights out people have logged there. */
            logCount: number;
            name: string;
        };
        addCommentRequest: {
            body: string;
        };
        apiError: {
            code: string;
            message: string;
        };
        createDjRequest: {
            bio: string;
            genres: string[];
            imageUrl: string;
            name: string;
            spotifyId: string;
        };
        createNightLogRequest: {
            city: string;
            djReviews: components["schemas"]["djReviewInput"][];
            eventId: string;
            eventName: string;
            /** @description When you went: day, night, or both. Neither given means night. */
            isDay: boolean;
            isNight: boolean;
            /**
             * @description DJs you saw. DJs in djReviews are added too, whether or not they're
             *     listed here.
             */
            lineupDjIds: string[];
            /** @description Review of the night as a whole. Required unless djReviews has one. */
            night: components["schemas"]["nightReviewInput"];
            placeId: string;
            placeSessionToken: string;
            seenAt: string;
            taggedUserIds: string[];
            /**
             * @description Tag names and tagged friends go on the night review, or on every DJ
             *     review when there's no night review.
             */
            tags: string[];
            venue: string;
            venueId: string;
        };
        djReviewInput: {
            djId: string;
            rating: number;
            reviewText: string;
        };
        errorEnvelope: {
            error: components["schemas"]["apiError"];
        };
        nightReviewInput: {
            rating: number;
            reviewText: string;
        };
        pushTokenRequest: {
            /** @description "ios" or "android"; ignored on unregister. */
            platform: string;
            /** @description An Expo push token (ExponentPushToken[...]). */
            token: string;
        };
        setFavoritesRequest: {
            reviewIds: string[];
        };
        updateProfileRequest: {
            avatarUrl: string;
            bio: string;
            displayName: string;
            username: string;
        };
        updateReviewRequest: {
            rating: number;
            reviewText: string;
            taggedUserIds: string[];
            /**
             * @description Tag names (new ones are added to the library). Omitted = leave
             *     as-is, [] = clear - same contract as TaggedUserIDs.
             */
            tags: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description the device's push token */
        pushTokenRequest: {
            content: {
                "application/json": components["schemas"]["pushTokenRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
