// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/app-version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "Minimum supported native app build, for the client's force-update check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AppVersionResponse"
                        }
                    }
                }
            }
        },
        "/api/comments/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Delete a comment owned by the caller (404, never 403, if not owned/found)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "comment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/djs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "djs"
                ],
                "summary": "Create a DJ (or return the existing one, deduped by spotifyId then slug)",
                "parameters": [
                    {
                        "description": "DJ to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createDjRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Dj"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/djs/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "djs"
                ],
                "summary": "Search DJs by name, most-reviewed first",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search; omit for the most-reviewed DJs",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max results, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Dj"
                            }
                        }
                    }
                }
            }
        },
        "/api/djs/spotify-search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "djs"
                ],
                "summary": "Search Spotify for artists (fails open to [] on Spotify errors)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SpotifyArtist"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/djs/{id}/reviews": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "djs"
                ],
                "summary": "List reviews for a DJ, cursor-paginated by seenAt desc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DJ id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagination cursor (RFC3339 seenAt of the last item)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedReviews"
                        }
                    }
                }
            }
        },
        "/api/djs/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "djs"
                ],
                "summary": "Get a DJ by slug, with rating aggregate and recent reviews",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DJ slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DjDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/events": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The venue is resolved from venueId, then placeId (a Google Places id, saved as a venue on first use), then the typed venue name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create an event (or return the existing one, deduped by exact name+venue+date)",
                "parameters": [
                    {
                        "description": "event to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/events/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Search events by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Event"
                            }
                        }
                    }
                }
            }
        },
        "/api/events/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get a night by id, with its series, lineup, and all its reviews",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EventDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/feed": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feed"
                ],
                "summary": "Activity feed: followed users' reviews interleaved with popular ones every 4th item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagination cursor (opaque, encodes createdAt + popular-pool offset)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FeedResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/feed/popular": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feed"
                ],
                "summary": "Most-liked-and-commented reviews, ranked",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page size, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PopularResponse"
                        }
                    }
                }
            }
        },
        "/api/follows/is-following/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Whether the caller follows the given user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FollowingStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/follows/{userId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Follow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id to follow",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Unfollow a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id to unfollow",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/leaderboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Leaderboard scoped to the caller and everyone they follow",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/LeaderboardEntry"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/logs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Log a night: find or create the night, add DJs to its lineup, and save the night and DJ reviews in one go",
                "parameters": [
                    {
                        "description": "the night to log",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createNightLogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/NightLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/reviews": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Create a review of a DJ (optionally tied to an event)",
                "parameters": [
                    {
                        "description": "review to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Review"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/reviews/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Get a review with its relations, engagement, and tagged users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ReviewDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Delete a review owned by the caller (404, never 403, if not owned/found)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Update a review owned by the caller (404, never 403, if not owned/found)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/updateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Review"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/reviews/{id}/comments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "List a review's comments, oldest first",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ReviewComment"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Add a comment to a review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "comment body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/addCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ReviewComment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/reviews/{id}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Like a review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Unlike a review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/series": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "List event series (recurring events like \"Innervisions\"), most-reviewed first",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search; omit to list all",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max results, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SeriesSummary"
                            }
                        }
                    }
                }
            }
        },
        "/api/series/{slug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Get an event series with its nights, DJs, venues, and recent reviews",
                "parameters": [
                    {
                        "type": "string",
                        "description": "series slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SeriesDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/tags": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List the tag library (defaults plus every tag users have added), most used first",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter to tags containing this text",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max results, 1-50, default 30",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TagSummary"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the caller's own user row",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update the caller's own profile",
                "parameters": [
                    {
                        "description": "fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/updateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/users/me/favorites": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Replace the caller's showcased favorite reviews (0-3, ordered, #1 first) - reviews must be the caller's own",
                "parameters": [
                    {
                        "description": "ordered review ids, at most 3, no duplicates",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/setFavoritesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FavoriteReviewsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/users/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Search users by username or display name, most-followed first",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search; omit for the most-followed users",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max results, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/User"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{userId}/followers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "List the users who follow the given user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/User"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{userId}/following": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "List the users the given user follows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/User"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{username}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user's profile by username, with follow/review counts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/users/{username}/favorites": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user's showcased favorite reviews (top 3, ordered, #1 first)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FavoriteReviewsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/users/{username}/reviews": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "List a user's reviews, cursor-paginated by seenAt desc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagination cursor (RFC3339 seenAt of the last item)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedReviews"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/users/{username}/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a user's review stats: totals, top DJs, top venues",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserStatsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/venues/places-search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Pass the same client-generated sessionToken on every keystroke of one search and on the POST /api/events that saves the picked place, so Google bills them as one session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venues"
                ],
                "summary": "Search Google Places for venues not yet saved",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Places autocomplete session token",
                        "name": "sessionToken",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/PlaceSuggestion"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/venues/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venues"
                ],
                "summary": "Search saved venues by name, busiest first",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search; omit for the busiest venues",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max results, 1-50, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/VenueSummary"
                            }
                        }
                    }
                }
            }
        },
        "/api/venues/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venues"
                ],
                "summary": "Get a venue by id, with its events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "venue id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VenueDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AppVersionResponse": {
            "type": "object",
            "required": [
                "iosUpdateUrl",
                "minIosBuild"
            ],
            "properties": {
                "iosUpdateUrl": {
                    "type": "string"
                },
                "minIosBuild": {
                    "type": "integer"
                }
            }
        },
        "Dj": {
            "type": "object",
            "required": [
                "bio",
                "createdAt",
                "createdByUserId",
                "genres",
                "id",
                "imageUrl",
                "name",
                "slug",
                "spotifyId",
                "updatedAt"
            ],
            "properties": {
                "bio": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdByUserId": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "spotifyId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "DjDetailResponse": {
            "type": "object",
            "required": [
                "avgRating",
                "dj",
                "recentReviews",
                "reviewCount"
            ],
            "properties": {
                "avgRating": {
                    "type": "number"
                },
                "dj": {
                    "$ref": "#/definitions/Dj"
                },
                "recentReviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                },
                "reviewCount": {
                    "type": "integer"
                }
            }
        },
        "Event": {
            "type": "object",
            "required": [
                "city",
                "createdAt",
                "createdByUserId",
                "description",
                "eventDate",
                "id",
                "isDay",
                "isNight",
                "name",
                "seriesId",
                "venue",
                "venueId"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdByUserId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDay": {
                    "description": "IsDay and IsNight say when the party ran; both is day into night.\nAt least one is set.",
                    "type": "boolean"
                },
                "isNight": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "seriesId": {
                    "description": "SeriesID is nil for a night that isn't part of a named event.",
                    "type": "string"
                },
                "venue": {
                    "description": "Venue is the venue's display name, kept denormalized alongside\nVenueID so existing displays don't need a join.",
                    "type": "string"
                },
                "venueId": {
                    "type": "string"
                }
            }
        },
        "EventDetailResponse": {
            "type": "object",
            "required": [
                "event",
                "lineup",
                "reviews",
                "series"
            ],
            "properties": {
                "event": {
                    "$ref": "#/definitions/Event"
                },
                "lineup": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Dj"
                    }
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                },
                "series": {
                    "description": "Series is nil for a night that isn't part of a named event.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/EventSeries"
                        }
                    ]
                }
            }
        },
        "EventSeries": {
            "type": "object",
            "required": [
                "createdAt",
                "createdByUserId",
                "id",
                "name",
                "slug"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdByUserId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "FavoriteReviewsResponse": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                }
            }
        },
        "FeedResponse": {
            "type": "object",
            "required": [
                "followingCount",
                "items",
                "nextCursor"
            ],
            "properties": {
                "followingCount": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                },
                "nextCursor": {
                    "type": "string"
                }
            }
        },
        "FollowingStatusResponse": {
            "type": "object",
            "required": [
                "following"
            ],
            "properties": {
                "following": {
                    "type": "boolean"
                }
            }
        },
        "LeaderboardEntry": {
            "type": "object",
            "required": [
                "reviewCount",
                "user"
            ],
            "properties": {
                "reviewCount": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/User"
                }
            }
        },
        "NightLogResponse": {
            "type": "object",
            "required": [
                "event",
                "reviews",
                "series"
            ],
            "properties": {
                "event": {
                    "$ref": "#/definitions/Event"
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Review"
                    }
                },
                "series": {
                    "$ref": "#/definitions/EventSeries"
                }
            }
        },
        "PaginatedReviews": {
            "type": "object",
            "required": [
                "items",
                "nextCursor"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                },
                "nextCursor": {
                    "type": "string"
                }
            }
        },
        "PlaceSuggestion": {
            "type": "object",
            "required": [
                "name",
                "placeId",
                "secondaryText"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "placeId": {
                    "type": "string"
                },
                "secondaryText": {
                    "description": "SecondaryText is the rest of the place's description, usually its\nstreet address and city.",
                    "type": "string"
                }
            }
        },
        "PopularResponse": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                }
            }
        },
        "Review": {
            "type": "object",
            "required": [
                "createdAt",
                "djId",
                "eventId",
                "id",
                "rating",
                "reviewText",
                "seenAt",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "djId": {
                    "description": "DjID is nil for a review of the night as a whole (EventID is then set).",
                    "type": "string"
                },
                "eventId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "reviewText": {
                    "type": "string"
                },
                "seenAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ReviewComment": {
            "type": "object",
            "required": [
                "body",
                "createdAt",
                "id",
                "reviewId",
                "userId"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reviewId": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/User"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ReviewDTO": {
            "type": "object",
            "required": [
                "createdAt",
                "djId",
                "eventId",
                "id",
                "rating",
                "reviewText",
                "seenAt",
                "taggedUsers",
                "tags",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "commentCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "dj": {
                    "$ref": "#/definitions/Dj"
                },
                "djId": {
                    "description": "DjID is nil for a review of the night as a whole (EventID is then set).",
                    "type": "string"
                },
                "event": {
                    "$ref": "#/definitions/Event"
                },
                "eventId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isLikedByMe": {
                    "type": "boolean"
                },
                "isPopular": {
                    "type": "boolean"
                },
                "likeCount": {
                    "type": "integer"
                },
                "lineupDj": {
                    "description": "LineupDj is set on a night review (no Dj) when the night's lineup is\nexactly one DJ, so it can be titled \"\u003cDJ\u003e at \u003cevent\u003e\".",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Dj"
                        }
                    ]
                },
                "rating": {
                    "type": "integer"
                },
                "reviewText": {
                    "type": "string"
                },
                "seenAt": {
                    "type": "string"
                },
                "taggedUsers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/User"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/User"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "SeriesDetailResponse": {
            "type": "object",
            "required": [
                "djs",
                "nights",
                "recentReviews",
                "series",
                "venues"
            ],
            "properties": {
                "djs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SeriesDj"
                    }
                },
                "nights": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SeriesNight"
                    }
                },
                "recentReviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ReviewDTO"
                    }
                },
                "series": {
                    "$ref": "#/definitions/SeriesSummary"
                },
                "venues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SeriesVenue"
                    }
                }
            }
        },
        "SeriesDj": {
            "type": "object",
            "required": [
                "dj",
                "nightCount"
            ],
            "properties": {
                "dj": {
                    "$ref": "#/definitions/Dj"
                },
                "nightCount": {
                    "type": "integer"
                }
            }
        },
        "SeriesNight": {
            "type": "object",
            "required": [
                "avgRating",
                "event",
                "reviewCount"
            ],
            "properties": {
                "avgRating": {
                    "type": "number"
                },
                "event": {
                    "$ref": "#/definitions/Event"
                },
                "reviewCount": {
                    "type": "integer"
                }
            }
        },
        "SeriesSummary": {
            "type": "object",
            "required": [
                "avgRating",
                "createdAt",
                "createdByUserId",
                "id",
                "name",
                "nightCount",
                "reviewCount",
                "slug"
            ],
            "properties": {
                "avgRating": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdByUserId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nightCount": {
                    "type": "integer"
                },
                "reviewCount": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "SeriesVenue": {
            "type": "object",
            "required": [
                "city",
                "id",
                "name",
                "nightCount"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nightCount": {
                    "type": "integer"
                }
            }
        },
        "SpotifyArtist": {
            "type": "object",
            "required": [
                "genres",
                "imageUrl",
                "name",
                "spotifyId"
            ],
            "properties": {
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "spotifyId": {
                    "type": "string"
                }
            }
        },
        "SuccessResponse": {
            "type": "object",
            "required": [
                "success"
            ],
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "TagSummary": {
            "type": "object",
            "required": [
                "id",
                "isDefault",
                "name",
                "useCount"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "useCount": {
                    "type": "integer"
                }
            }
        },
        "TopDj": {
            "type": "object",
            "required": [
                "dj",
                "reviewCount"
            ],
            "properties": {
                "dj": {
                    "$ref": "#/definitions/Dj"
                },
                "reviewCount": {
                    "type": "integer"
                }
            }
        },
        "TopVenue": {
            "type": "object",
            "required": [
                "reviewCount",
                "venue"
            ],
            "properties": {
                "reviewCount": {
                    "type": "integer"
                },
                "venue": {
                    "type": "string"
                }
            }
        },
        "User": {
            "type": "object",
            "required": [
                "avatarUrl",
                "bio",
                "createdAt",
                "displayName",
                "id",
                "updatedAt",
                "username"
            ],
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "UserProfileResponse": {
            "type": "object",
            "required": [
                "followerCount",
                "followingCount",
                "reviewCount",
                "user"
            ],
            "properties": {
                "followerCount": {
                    "type": "integer"
                },
                "followingCount": {
                    "type": "integer"
                },
                "reviewCount": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/User"
                }
            }
        },
        "UserStatsResponse": {
            "type": "object",
            "required": [
                "topDjs",
                "topVenues",
                "totalReviews",
                "uniqueDjs"
            ],
            "properties": {
                "topDjs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TopDj"
                    }
                },
                "topVenues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TopVenue"
                    }
                },
                "totalReviews": {
                    "type": "integer"
                },
                "uniqueDjs": {
                    "type": "integer"
                }
            }
        },
        "VenueDetailResponse": {
            "type": "object",
            "required": [
                "events",
                "venue"
            ],
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Event"
                    }
                },
                "venue": {
                    "$ref": "#/definitions/VenueSummary"
                }
            }
        },
        "VenueSummary": {
            "type": "object",
            "required": [
                "address",
                "city",
                "eventCount",
                "googlePlaceId",
                "id",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "eventCount": {
                    "type": "integer"
                },
                "googlePlaceId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "addCommentRequest": {
            "type": "object",
            "required": [
                "body"
            ],
            "properties": {
                "body": {
                    "type": "string"
                }
            }
        },
        "apiError": {
            "type": "object",
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "createDjRequest": {
            "type": "object",
            "required": [
                "bio",
                "genres",
                "imageUrl",
                "name",
                "spotifyId"
            ],
            "properties": {
                "bio": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "spotifyId": {
                    "type": "string"
                }
            }
        },
        "createEventRequest": {
            "type": "object",
            "required": [
                "city",
                "description",
                "eventDate",
                "name",
                "placeId",
                "placeSessionToken",
                "venue",
                "venueId"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "placeId": {
                    "type": "string"
                },
                "placeSessionToken": {
                    "type": "string"
                },
                "venue": {
                    "type": "string"
                },
                "venueId": {
                    "type": "string"
                }
            }
        },
        "createNightLogRequest": {
            "type": "object",
            "required": [
                "city",
                "djReviews",
                "isDay",
                "isNight",
                "lineupDjIds",
                "night",
                "placeId",
                "placeSessionToken",
                "seenAt",
                "seriesId",
                "seriesName",
                "taggedUserIds",
                "tags",
                "venue",
                "venueId"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "djReviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/djReviewInput"
                    }
                },
                "isDay": {
                    "description": "When the party ran: day, night, or both. Neither given means night.",
                    "type": "boolean"
                },
                "isNight": {
                    "type": "boolean"
                },
                "lineupDjIds": {
                    "description": "DJs the user saw; added to the night's lineup. DJs in djReviews are\nadded too, whether or not they're listed here.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "night": {
                    "description": "Review of the night as a whole. Required unless djReviews has one.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/nightReviewInput"
                        }
                    ]
                },
                "placeId": {
                    "type": "string"
                },
                "placeSessionToken": {
                    "type": "string"
                },
                "seenAt": {
                    "type": "string"
                },
                "seriesId": {
                    "type": "string"
                },
                "seriesName": {
                    "type": "string"
                },
                "taggedUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "description": "Tag names and tagged friends go on the night review, or on every DJ\nreview when there's no night review.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "venue": {
                    "type": "string"
                },
                "venueId": {
                    "type": "string"
                }
            }
        },
        "createReviewRequest": {
            "type": "object",
            "required": [
                "djId",
                "eventId",
                "rating",
                "reviewText",
                "seenAt",
                "taggedUserIds",
                "tags"
            ],
            "properties": {
                "djId": {
                    "type": "string"
                },
                "eventId": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "reviewText": {
                    "type": "string"
                },
                "seenAt": {
                    "type": "string"
                },
                "taggedUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "description": "Tag names (new ones are added to the library). Omitted = leave\nas-is, [] = clear - same contract as TaggedUserIDs.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "djReviewInput": {
            "type": "object",
            "required": [
                "djId",
                "rating",
                "reviewText"
            ],
            "properties": {
                "djId": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "reviewText": {
                    "type": "string"
                }
            }
        },
        "errorEnvelope": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "$ref": "#/definitions/apiError"
                }
            }
        },
        "nightReviewInput": {
            "type": "object",
            "required": [
                "rating",
                "reviewText"
            ],
            "properties": {
                "rating": {
                    "type": "integer"
                },
                "reviewText": {
                    "type": "string"
                }
            }
        },
        "setFavoritesRequest": {
            "type": "object",
            "required": [
                "reviewIds"
            ],
            "properties": {
                "reviewIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "updateProfileRequest": {
            "type": "object",
            "required": [
                "avatarUrl",
                "bio",
                "displayName",
                "username"
            ],
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "updateReviewRequest": {
            "type": "object",
            "required": [
                "rating",
                "reviewText",
                "seenAt",
                "taggedUserIds",
                "tags"
            ],
            "properties": {
                "rating": {
                    "type": "integer"
                },
                "reviewText": {
                    "type": "string"
                },
                "seenAt": {
                    "type": "string"
                },
                "taggedUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "description": "Tag names (new ones are added to the library). Omitted = leave\nas-is, [] = clear - same contract as TaggedUserIDs.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Clerk-issued session JWT, e.g. \"Bearer eyJhbGc...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Beatboxd API",
	Description:      "REST API for Beatboxd (Letterboxd for DJ sets). Generated from\nserver/internal/httpapi handler annotations via swag - run\n`make openapi` in server/ to regenerate after changing a handler.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
